/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Owner
 */
public class showModems extends javax.swing.JFrame {
    public static List<String> DV = new ArrayList<>();
    UpdateDetails device;
    /**
     * Creates new form showModems
     */
    public showModems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        topSep = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        comm = new javax.swing.JComboBox();
        btSep = new javax.swing.JSeparator();
        antena_lb = new javax.swing.JLabel();
        antena = new javax.swing.JProgressBar();
        company_lb = new javax.swing.JLabel();
        company = new javax.swing.JLabel();
        imei_lb = new javax.swing.JLabel();
        imei = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        show = new javax.swing.JButton();

        setTitle("Detalles de Modem");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel.add(topSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 238, -1));

        titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titulo.setText("Detalles de Modems :");
        panel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        comm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-  -  -  -" }));
        panel.add(comm, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 10, 100, 20));
        panel.add(btSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 238, -1));

        antena_lb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        antena_lb.setText("Nivel de Señal de Antena : ");
        panel.add(antena_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        panel.add(antena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, 238, 40));

        company_lb.setText("Compañia : ");
        panel.add(company_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        company.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        company.setText("  -  -  -  -  -  -  ");
        panel.add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 238, -1));

        imei_lb.setText("S/N IMEI :");
        panel.add(imei_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        imei.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        imei.setText("  -  -  -  -  -  -  ");
        panel.add(imei, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 238, -1));

        update.setText("Actualizar");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        panel.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 48, 110, 32));

        show.setText("Mostrar");
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        panel.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 110, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        if(update.isEnabled())
        new ListPorts();
    }//GEN-LAST:event_updateMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        if(show.isEnabled()){
            device = new UpdateDetails(DV.get(comm.getSelectedIndex()));
            device.run();
        }
    }//GEN-LAST:event_showMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showModems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showModems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showModems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showModems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    System.out.println("Unable to set native look and feel: " + e);
                }
                new showModems().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar antena;
    private javax.swing.JLabel antena_lb;
    private javax.swing.JSeparator btSep;
    public static javax.swing.JComboBox comm;
    public static javax.swing.JLabel company;
    private javax.swing.JLabel company_lb;
    public static javax.swing.JLabel imei;
    private javax.swing.JLabel imei_lb;
    private javax.swing.JPanel panel;
    public static javax.swing.JButton show;
    private javax.swing.JLabel titulo;
    private javax.swing.JSeparator topSep;
    public static javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
